name: Tag - Memo MDH
on:
  push:
    branches:
      - main
    paths:
      - dist/memo_mdh/**
jobs:
  call-reusable:
    uses: ./.github/workflows/_tag_release.yml
    with:
      tag_prefix: "ext/memo_mdh/v"
